# Generated by Django 5.2.7 on 2025-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='emergency_panic_button', max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('audio_url', models.URLField()),
                ('notified_contacts', models.JSONField(blank=True, default=list)),
                ('delivered_to_authorities', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
