# Generated by Django 5.2.7 on 2025-10-05 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('extremely_dangerous', 'Extremely Dangerous'), ('dangerous', 'Dangerous'), ('relatively_unsafe', 'Relatively Unsafe'), ('accident_zone', 'Accident Zone'), ('wildlife_danger', 'Wildlife Danger')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=100.0, help_text='Radius in meters')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
